[project]
name = "cardlink"
version = "0.1.0"
description = "Wrapper for the Cardlink API in Python"
readme = "README.md"
keywords = ["cardlink", "api", "async", "httpx", "pydantic"]
requires-python = ">=3.10"
dependencies = [
    "httpx[cli]>=0.28.1",
    "pydantic>=2.13.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cardlink"]